import { StyleSheet } from "react-native";

export default StyleSheet.create({
  button: {
    borderRadius: 10,
    backgroundColor: "#383838",
    height: 46,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
  },
  buttonTitle: {
    color: "#FFF",
    fontFamily: "Roboto",
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "500",
    lineHeight: 21.6,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: "rgba(126, 126, 126, 0.50)",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    width: "100%",
    height: 458,
  },
  closeButton: {
    marginTop: 10,
    backgroundColor: "blue",
    padding: 10,
    borderRadius: 5,
  },
  input: {
    borderRadius: 10,
    backgroundColor: "#F5F5F5",
    height: 50,
    paddingStart: 11,
    paddingVertical: 14,
    color: "#7C7C7C",
    fontFamily: "Roboto",
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 21.6,
  },
  headerTitle: {
    color: "#4F4F4F",
    fontFamily: "Roboto",
    fontSize: 18,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 21.6,
    width: "80%",
    textAlign: "center",
  },
  title: {
    color: "#939393",
    fontFamily: "Roboto",
    fontSize: 16,
    fontStyle: "normal",
    fontWeight: "400",
    lineHeight: 19.2,
    marginTop: 46,
    marginBottom: 38,
    width: 344,
  },
});
